mqttbroker:
  broker: raspberrypi.lan
  port: 1883
  TLS: False
  KeepAlive: 60
  mqtt-topics:
    holes:
      - h1
      - h2
    lights:
      - l1
      - l2

gamesettings:
  colours:
    - red
    - green
    - blue
  nHoles: 6
  difficulty: 1
  gametime: 10
